version : "3.7"
services :
  microservicio :
    container_name : microservicio
    image : microservicio:v1
    build : 
      context : .
    ports : 
      - "4001:4001"
    networks : 
     - proyectos-app

networks : 
  proyectos-app :